#!/usr/bin/env bash
# Drives mylo through a realistic reading cycle for a sustained period and
# records managed heap and process resident set throughout, so "does it leak
# when left running" can be answered from numbers rather than from a feeling.
#
# Usage: ux-scripts/run-memory-soak.sh [output-dir] [iterations]
#
# Defaults to /tmp/lr-memory-soak and 300 iterations, which is roughly
# twenty-two minutes. Do not shorten it and expect an answer: the summary
# refuses to give a verdict until the run has both enough steady-state
# samples and enough gen2 collections to have a live-set measurement at all,
# and a five-minute run of this app has neither. It will still run, and still
# print its table; it will say the run was too short rather than guess.
#
# Every part of it is repeatable: a throwaway MYLO_DATA_DIR profile seeded
# from reader-fixture.sql, deleted from an EXIT/INT/TERM trap along with the
# background churn loop, exactly like every other script here.
#
# WHAT IS AND IS NOT REAL ABOUT THIS RUN, because it decides what the numbers
# mean.
#
# The UI cycle is real: selecting sidebar rows, opening articles, searching,
# switching filters and pressing Refresh all, hundreds of times over.
# That is what actually allocates in this app - ItemRow and FeedTreeNode
# objects rebuilt from scratch on every load, bitmaps decoded through
# PathToBitmapConverter, snippets, status strings.
#
# The refreshes are real too, and they fail. The fixture's feed addresses are
# under .test, which resolves nowhere, so every sweep exercises the whole
# refresh path - the coordinator, the in-flight set, the backoff write, the
# Completed event, the auto-pause counter - and records a failure at the end
# of it. That is the path a long-running reader spends most of its life on
# anyway; a feed that answers 304 is cheaper than one that fails.
#
# What is NOT real is articles arriving over HTTP, and that is by design
# rather than by omission. FeedUrlPolicy refuses loopback and every private
# range, and PolicyHttpHandler applies it under every request the app makes,
# so a local stub feed server is unreachable from this app by construction -
# which is the correct behaviour and not something to weaken for a test. New
# articles are therefore inserted straight into the seeded database by the
# churn loop below, three at a time, with the three oldest removed so the item
# count stays flat. A growing table would grow the heap legitimately and there
# would be nothing left to measure.
#
# The churn loop also clears the failure counters each pass. Without that the
# fixture's feeds auto-pause after twenty consecutive failures and the refresh
# path goes quiet for the rest of the run, which would take the busiest code
# path out of the very soak meant to exercise it.
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/reader-harness.sh"

OUTPUT="${1:-/tmp/lr-memory-soak}"
ITERATIONS="${2:-300}"

reader_require_app
mkdir -p "$OUTPUT"

READER_PROFILE="$(mktemp -d)"
CHURN_PID=""

cleanup() {
    [[ -n "$CHURN_PID" ]] && kill "$CHURN_PID" 2>/dev/null || true
    rm -rf "$READER_PROFILE"
}
trap cleanup EXIT INT TERM

reader_seed_profile "$READER_PROFILE"

# Refreshing on, at the five minute floor, so the scheduler's own timer runs
# for the whole soak alongside the Refresh all presses the script makes.
python3 - "$READER_PROFILE/settings.json" <<'PY'
import json, sys
path = sys.argv[1]
with open(path) as handle:
    settings = json.load(handle)
settings["refreshOnStartup"] = True
settings["defaultRefreshIntervalMinutes"] = 5
with open(path, "w") as handle:
    json.dump(settings, handle, indent=2)
PY

# ---------------------------------------------------------------------------
# The generated driving script. One cycle per iteration, written out rather
# than looped, because the YAML the harness reads has no loop construct.
# ---------------------------------------------------------------------------
python3 - "$READER_PROFILE/soak.yaml" "$ITERATIONS" <<'PY'
import sys

path, iterations = sys.argv[1], int(sys.argv[2])

header = """name: memory-soak
description: >
  A reading cycle repeated many times, to measure whether anything grows.
  Generated by ux-scripts/run-memory-soak.sh; do not edit by hand.
default_delay: 60
actions:
  - type: Wait
    value: "2500"
"""

# Deliberately no Screenshot actions. A capture per cycle would dominate both
# the time and the allocation, and the question here is what the reading path
# itself retains.
cycle = """
  - type: MouseDown
    target: "inside(name=SidebarSections) text='All items'"
    button: left
  - type: MouseUp
    target: "inside(name=SidebarSections) text='All items'"
    button: left
  - type: Wait
    value: "300"
  - type: MouseDown
    target: "inside(name=SidebarSections) text='Harness Alpha'"
    button: left
  - type: MouseUp
    target: "inside(name=SidebarSections) text='Harness Alpha'"
    button: left
  - type: Wait
    value: "300"
  - type: MouseDown
    target: "inside(name=SidebarSections) text='Unread'"
    button: left
  - type: MouseUp
    target: "inside(name=SidebarSections) text='Unread'"
    button: left
  - type: Wait
    value: "300"
  - type: Click
    target: SearchBox
  - type: TypeText
    target: SearchBox
    value: harness
  - type: Wait
    value: "500"
  - type: MouseDown
    target: "inside(name=SidebarSections) text='All items'"
    button: left
  - type: MouseUp
    target: "inside(name=SidebarSections) text='All items'"
    button: left
  - type: Wait
    value: "400"
  - type: Click
    target: RefreshAllButton
  - type: Wait
    value: "700"
"""

with open(path, "w") as handle:
    handle.write(header)
    handle.write(cycle * iterations)
PY

# ---------------------------------------------------------------------------
# The churn loop: keeps articles arriving, keeps the item count flat, and
# keeps the feeds out of auto-pause. Backgrounded, killed from the trap.
# ---------------------------------------------------------------------------
(
    round=0
    while true; do
        sleep 20
        round=$((round + 1))
        sqlite3 "$READER_PROFILE/reader.db" <<SQL 2>/dev/null || true
PRAGMA foreign_keys=ON;
INSERT OR IGNORE INTO items (feed_id, guid, title, summary, first_seen_utc, published_utc, content_source, offline_state)
SELECT id, 'soak-$round-' || id || '-a', 'Soak article $round a', 'Body text for the soak run, round $round.',
       strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'), 0, 0 FROM feeds;
INSERT OR IGNORE INTO items (feed_id, guid, title, summary, first_seen_utc, published_utc, content_source, offline_state)
SELECT id, 'soak-$round-' || id || '-b', 'Soak article $round b', 'Body text for the soak run, round $round.',
       strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'), 0, 0 FROM feeds;
DELETE FROM items WHERE id IN (
    SELECT id FROM items ORDER BY COALESCE(published_utc, first_seen_utc) ASC
    LIMIT MAX(0, (SELECT COUNT(*) FROM items) - 60));
UPDATE feeds SET is_enabled = 1, consecutive_failures = 0, auto_paused_utc = NULL, next_due_utc = NULL;
SQL
    done
) &
CHURN_PID=$!

echo "Soaking for $ITERATIONS cycles. Log: $OUTPUT/memory.csv"

# Headless by default, the same default reader_run uses and for the same
# reason: this script drives the app for twenty-two minutes, and on the native
# platform that is twenty-two minutes of a window holding keyboard focus. This
# line launched the app directly and so missed that default, which made this
# the one script in ux-scripts/ that put a window on screen. Set MYLO_UX_MODE
# to watch a run happen.
MYLO_DATA_DIR="$READER_PROFILE" \
MYLO_MEMORY_LOG="$OUTPUT/memory.csv" \
MYLO_MEMORY_LOG_SECONDS=5 \
    "$READER_APP" "${MYLO_UX_MODE:---ux-headless}" --ux-test \
    --script "$READER_PROFILE/soak.yaml" \
    --output "$OUTPUT" || true

# The database's own footprint at the end of the run, which is the other half
# of "does it grow": the -wal in particular used to sit at its high-water mark
# for a whole session because a passive checkpoint never shortens it.
{
    echo
    echo "Database files at the end of the run:"
    ls -l "$READER_PROFILE"/reader.db* 2>/dev/null || true
} | tee "$OUTPUT/database-size.txt"

python3 "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/summarise-memory.py" "$OUTPUT/memory.csv"
